# -*- coding: utf-8 -*-
"""covid_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5v9lvi_VnlwJ1MP5i9g8Z9JuPbHUMaR

# Name: Sonali Jha
# Course: B.sc hons Computer science
# Covid Data Analysis Using Folium
"""

import pandas as pd
import numpy as np
df=pd.read_csv(r"/content/country_wise_latest.csv")
df.head()

df.info()

df.rename(columns={'Country/Region':'Country'},inplace = True)
countries = df['Country'].unique().tolist()
print(countries)

print("\nTotal countries affected by virus: ",len(countries))

pip install folium

import folium

world_data=pd.read_csv(r"/content/world_coordinates.csv")

Number_of_countries = len(df['Country'].value_counts())
cases = pd.DataFrame(df.groupby('Country')['Confirmed'].sum())
cases['Country'] = cases.index
cases.index=np.arange(1,Number_of_countries+1)
global_cases = cases[['Country','Confirmed']]
world_data = pd.merge(world_data,global_cases,on='Country')
world_data.head()

import folium

# create map and display it
world_map = folium.Map(location=[10, -20], zoom_start=2.3, tiles='CartoDB positron')

for lat, lon, value, name in zip(world_data['latitude'], world_data['longitude'], world_data['Confirmed'], world_data['Country']):
    folium.CircleMarker(
        [lat, lon],
        radius=10,
        popup=(
            f'<strong>Country</strong>: {str(name).capitalize()}<br>'
            f'<strong>Confirmed Cases</strong>: {str(value)}<br>'
        ),
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7
    ).add_to(world_map)

world_map

